variables:
    TUTOR_PLUGIN: bl
    TUTOR_EXTRA_ENABLED_PLUGINS: mfe
    TUTOR_PYPI_PACKAGE: tutor-bl
    TUTOR_IMAGES: openedx mfe
    OPENEDX_RELEASE: quince
    GITHUB_REPO: blend-ed/tutor-indigo-palm

include:
  - project: 'community/tutor-ci'
    file: 'plugin-gitlab-ci.yml'
